spring:
  datasource:
    url: jdbc:postgresql://dev-database.cymzgghogy1u.ap-northeast-2.rds.amazonaws.com/chuk_check
    username: fcprovin
    password: vmfhqls!6
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging.level:
  org.hibernate.SQL: debug