spring:
  profiles:
    include:
    - jwt
  datasource:
    url: jdbc:h2:tcp://localhost/~/chuk-check
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging.level:
  org.hibernate.SQL: debug